[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.0", features = ["postgres", "chrono", "uuid"] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }
chrono = { version = "0.4.45", features = ["now"] }
serde_json = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
axum-login = "0.18.0"
dotenvy = "0.15"
